import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const dist = join(root, 'dist');
const themeStyles = [
  'tokens.css',
  'shell.css',
  'navigation.css',
  'article.css',
  'overlays.css',
  'responsive.css',
];

await rm(dist, { recursive: true, force: true });
await mkdir(join(dist, 'assets'), { recursive: true });
await Promise.all([
  cp(join(root, 'src', 'index.js'), join(dist, 'index.js')),
  cp(join(root, 'src', 'styles'), join(dist, 'styles'), { recursive: true }),
  cp(join(root, 'src', 'client.js'), join(dist, 'client.js')),
  cp(join(root, 'src', 'options.schema.json'), join(dist, 'options.schema.json')),
  cp(join(root, 'assets', 'registration-mark.svg'), join(dist, 'assets', 'registration-mark.svg')),
]);

// Quartz wraps theme-declared `styles` inside its base cascade layer. Keep the
// descriptor styles for API compatibility, and publish the same trusted CSS as
// an immutable local asset so the header can link it after Quartz's defaults.
// That preserves this theme's deliberate reading shell without changing the
// host renderer or relying on runtime downloads.
const cascade = (await Promise.all(themeStyles.map((style) =>
  readFile(join(root, 'src', 'styles', style), 'utf8')))).join('\n\n');
await writeFile(
  join(dist, 'assets', 'brutalist-cascade.css'),
  `/* Pages Publish Brutalist cascade guard: generated by scripts/build.mjs */\n${cascade}\n`,
);
